language: ruby

rvm:
  - 2.5

cache: bundler

before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium
  - sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo apt install libsodium-dev -y
  - gem install bundler -v '< 2'

addons:
  apt:
    update: true

script: "bundle exec rspec --color"